---
- hosts: all
  become: true
  tasks: 

  - name: update repository index
    ansible.builtin.dnf:
      update_cache: yes

  - name: remove httpd package
    ansible.builtin.dnf:
      name: httpd

  - name: remove PHP-FPM for httpd
    ansible.builtin.dnf:
      name: 
        - php
        - php-fpm
      state: absent
